### ISSUE TITLE
Cannot start GUI under Linux: FileNotFoundError

### ISSUE THREAD

**Issue by rchastain** [eligolf/endamat_chess#2]
Hello! I tried to start the GUI under Linux. I get this error:

```
[roland@localhost gui (main)]$ python3 gui_main.py
pygame 2.0.0 (SDL 2.0.14, python 3.8.12)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "gui_main.py", line 1094, in <module>
    Gui().main()
  File "gui_main.py", line 50, in __init__
    self.theme = Theme()
  File "/home/roland/Documents/echecs/sources/endamat/gui/gui_theme.py", line 22, in __init__
    self.icon = pygame.image.load(f'{self.path}/icon.ico')
FileNotFoundError: No such file or directory.
```

The engine alone seems to work correctly:
```
[roland@localhost endamat (main)]$ python uci.py
uci
id name Endamat Chess
id author Elias Nilsson
uciok
position startpos
go movetime 1000
info score cp 39 depth 1 nodes 20 time 2 pv d2-d4
info score cp 0 depth 2 nodes 112 time 14 pv d2-d4, d7-d5
info score cp 34 depth 3 nodes 1221 time 93 pv d2-d4, d7-d5, Ng1-f3
info score cp 0 depth 4 nodes 4803 time 475 pv d2-d4, Ng8-f6, Ng1-f3, d7-d5
bestmove d2d4
quit
```

Regards.
Roland

**Comment by eligolf** [comment]
Hi Roland, thanks for the report! 
It seems it can't find the icon file for some reason. I have not yet tried this on other OS than Windows. If you want it to work I guess you can comment out the self.icon row since it only places an icon on the window. Hopefully the rest of the images will load correctly.

**Comment by rchastain** [comment]
> If you want it to work I guess you can comment out the self.icon row since it only places an icon on the window. Hopefully the rest of the images will load correctly.

I had to replace `\\` with `/` everywhere in _gui/gui_theme.py_. After that, the application works under Linux.

Regards.

Roland

**Comment by eligolf** [comment]
Ok, maybe I will have to make it different for different OS. To be honest, the project is mostly just for fun but it would be nice if it worked outside of Windows as well :)

**Comment by rchastain** [comment]
Here is the modified file, in case you would try it. Maybe it will work also under Windows without modification (not tested).
[gui_theme.zip](https://github.com/eligolfer91/endamat_chess/files/8195031/gui_theme.zip)
